/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type PalSignatureStruct = {
  newAddress: PromiseOrValue<string>;
  transferDetails: ISignatureTransfer.SignatureTransferDetailsStruct[];
};

export type PalSignatureStructOutput = [
  string,
  ISignatureTransfer.SignatureTransferDetailsStructOutput[]
] & {
  newAddress: string;
  transferDetails: ISignatureTransfer.SignatureTransferDetailsStructOutput[];
};

export type BackupWitnessStruct = {
  signers: PromiseOrValue<string>[];
  threshold: PromiseOrValue<BigNumberish>;
};

export type BackupWitnessStructOutput = [string[], BigNumber] & {
  signers: string[];
  threshold: BigNumber;
};

export declare namespace TokenBackups {
  export type PalsStruct = {
    sigs: PromiseOrValue<BytesLike>[];
    addresses: PromiseOrValue<string>[];
  };

  export type PalsStructOutput = [string[], string[]] & {
    sigs: string[];
    addresses: string[];
  };
}

export declare namespace ISignatureTransfer {
  export type TokenPermissionsStruct = {
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type TokenPermissionsStructOutput = [string, BigNumber] & {
    token: string;
    amount: BigNumber;
  };

  export type PermitBatchTransferFromStruct = {
    permitted: ISignatureTransfer.TokenPermissionsStruct[];
    nonce: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
  };

  export type PermitBatchTransferFromStructOutput = [
    ISignatureTransfer.TokenPermissionsStructOutput[],
    BigNumber,
    BigNumber
  ] & {
    permitted: ISignatureTransfer.TokenPermissionsStructOutput[];
    nonce: BigNumber;
    deadline: BigNumber;
  };

  export type SignatureTransferDetailsStruct = {
    to: PromiseOrValue<string>;
    requestedAmount: PromiseOrValue<BigNumberish>;
  };

  export type SignatureTransferDetailsStructOutput = [string, BigNumber] & {
    to: string;
    requestedAmount: BigNumber;
  };
}

export interface TokenBackupsInterface extends utils.Interface {
  functions: {
    "recover((bytes[],address[]),bytes,((address,uint256)[],uint256,uint256),(address,(address,uint256)[]),(address[],uint256),address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "recover"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "recover",
    values: [
      TokenBackups.PalsStruct,
      PromiseOrValue<BytesLike>,
      ISignatureTransfer.PermitBatchTransferFromStruct,
      PalSignatureStruct,
      BackupWitnessStruct,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "recover", data: BytesLike): Result;

  events: {};
}

export interface TokenBackups extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenBackupsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    recover(
      pals: TokenBackups.PalsStruct,
      backup: PromiseOrValue<BytesLike>,
      permitData: ISignatureTransfer.PermitBatchTransferFromStruct,
      palData: PalSignatureStruct,
      witnessData: BackupWitnessStruct,
      oldAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  recover(
    pals: TokenBackups.PalsStruct,
    backup: PromiseOrValue<BytesLike>,
    permitData: ISignatureTransfer.PermitBatchTransferFromStruct,
    palData: PalSignatureStruct,
    witnessData: BackupWitnessStruct,
    oldAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    recover(
      pals: TokenBackups.PalsStruct,
      backup: PromiseOrValue<BytesLike>,
      permitData: ISignatureTransfer.PermitBatchTransferFromStruct,
      palData: PalSignatureStruct,
      witnessData: BackupWitnessStruct,
      oldAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    recover(
      pals: TokenBackups.PalsStruct,
      backup: PromiseOrValue<BytesLike>,
      permitData: ISignatureTransfer.PermitBatchTransferFromStruct,
      palData: PalSignatureStruct,
      witnessData: BackupWitnessStruct,
      oldAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    recover(
      pals: TokenBackups.PalsStruct,
      backup: PromiseOrValue<BytesLike>,
      permitData: ISignatureTransfer.PermitBatchTransferFromStruct,
      palData: PalSignatureStruct,
      witnessData: BackupWitnessStruct,
      oldAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
